### ISSUE TITLE
Installation issues on Win10

### ISSUE THREAD

**Issue by Nic2012** [GoogleChromeLabs/sw-appcache-behavior#28]
With the latest version I am not able to install project via npm on Win10, using node v9.11 or v12.13
```
E:\build\_appCache\sw-appcache-behavior-0.3.0>npm install
> puppeteer-firefox@0.5.1 install E:\build\_appCache\sw-appcache-behavior-0.3.0\node_modules\puppeteer-firefox
> node install.js
ERROR: Failed to download Firefox rv0.0.1!
Error: Download failed: server returned code 404. URL: https://github.com/puppeteer/juggler/releases/download/v0.0.1/firefox-win64.zip
    at response (E:\build\_appCache\sw-appcache-behavior-0.3.0\node_modules\puppeteer-firefox\lib\BrowserFetcher.js:264:21)
    at ClientRequest.requestCallback (E:\build\_appCache\sw-appcache-behavior-0.3.0\node_modules\puppeteer-firefox\lib\BrowserFetcher.js:320:7)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:180:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:540:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:445:20)
    at TLSSocket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (E:\build\_appCache\sw-appcache-behavior-0.3.0\node_modules\puppeteer-firefox\lib\helper.js:32:15)
    at Object.<anonymous> (E:\build\_appCache\sw-appcache-behavior-0.3.0\node_modules\puppeteer-firefox\install.js:47:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
...
```

After removing puppeteer and running npm run build I got errors that microbundle is missing or misspelled:
```
E:\build\_appCache\sw-appcache-behavior-0.3.0>npm run build

> index@0.0.0 build E:\build\_appCache\sw-appcache-behavior-0.3.0
> npm run build-sw && npm run build-window


> index@0.0.0 build-sw E:\build\_appCache\sw-appcache-behavior-0.3.0
> cd packages/appcache-polyfill-sw && npm run build && cd -


> appcache-polyfill-sw@0.3.0 build E:\build\_appCache\sw-appcache-behavior-0.3.0\packages\appcache-polyfill-sw
> npm run clean && microbundle --name=appcachePolyfill


> appcache-polyfill-sw@0.3.0 clean E:\build\_appCache\sw-appcache-behavior-0.3.0\packages\appcache-polyfill-sw
> rimraf build

Der Befehl "microbundle" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appcache-polyfill-sw@0.3.0 build: `npm run clean && microbundle --name=appcachePolyfill`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appcache-polyfill-sw@0.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by jeffposnick** [comment]
In the long run, moving off of `puppeteer-firefox` and onto a newer version of `puppeteer` that has Firefox support built-in will probably help with the first problem. I don't have much control over the `puppeteer-firefox` binary downloads.

Regarding the second issue, it sounds like you need to do an `npm ci` from the top-level directory to get a local copy of `node_modules` prior to running the build commands?

```
Local package.json exists, but node_modules missing, did you mean to install?
```
